# Generated by Django 4.2.13 on 2026-05-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_todo_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
